CREATE DATABASE my_DB;

CREATE TABLE Users (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login VARCHAR ( 50 ) CHECK(login !='') NOT NULL,
	password VARCHAR ( 50 ) CHECK(password !='' AND password ~ '^(?=.*[a-zA-Z])(?=.*[0-9])') NOT NULL,
	age INT CHECK (age >= 4 AND age <= 130) NOT NULL,	
	"isDeleted" BOOL NOT NULL
);

INSERT INTO Users (login, password, age, "isDeleted") VALUES ('logexamp1', 'password1', 30, false);
INSERT INTO Users (login, password, age, "isDeleted") VALUES ('logb', 'password2', 40, false);
INSERT INTO Users (login, password, age, "isDeleted") VALUES ('lin3', 'password3', 50, false);
INSERT INTO Users (login, password, age, "isDeleted") VALUES ('test4', 'password4', 60, true);
INSERT INTO Users (login, password, age, "isDeleted") VALUES ('loga', 'password5', 70, false);
